### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by MOOOOs** [henkelmax/sound-physics-remastered#68] opened 2022-09-23 17:48 UTC
**Bug description**
First noticed in nether that my framerate will drop to 1 fps if i get close to lava pool about 1 block away also slower loading times in both worlds if i remove this mod everything will be back to solid 60 fps

**Steps to reproduce the issue**
1. Go to 'Nether lava pool'

**Expected behavior**
it should not lag and be smooth 60 fps like i previously had and world loading times should be faster

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
[latest.log](https://github.com/henkelmax/sound-physics-remastered/files/9636114/latest.log)

**Versions**
- Minecraft version 1.19.2
- Forge/Fabric version Fabric 0.14.9
- Mod version 1.0.12

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment] 2022-09-23 17:51
Duplicate of #56.

**Closed by henkelmax** 2022-09-23 17:51 UTC
Labels: bug

**Comment by MOOOOs** [comment] 2022-09-23 17:53
So this is being fixed right now?

**Comment by henkelmax** [comment] 2022-09-23 17:54
This was already fixed a month ago. You are using an outdated version.

**Comment by henkelmax** [comment] 2022-09-23 17:55
No. You are using `1.0.12`.

**Comment by MOOOOs** [comment] 2022-09-23 17:56
its not latest? i installed it straight form curseforge two days ago it was latest

**Comment by henkelmax** [comment] 2022-09-23 17:57
Nope. `1.0.15` is the latest version since about a month.

**Comment by MOOOOs** [comment] 2022-09-23 17:57
thanks i downlaoded latest  version now :D
