### ISSUE TITLE
1.18.2 Disappearing sounds in Lan

### ISSUE THREAD

**Issue by BlackAures1** [henkelmax/sound-physics-remastered#54] opened 2022-07-30 11:47 UTC
**Bug description**
For some unknown reason, sometimes sounds randomly disappear or become very quiet when playing Lan for a long time. Perhaps it has to do with that moving between dimensions. In any case, regardless of the sound settings, I have sounds disappearing and appearing at the same time as the host.

**Steps to reproduce the issue**
Alas, I cannot tell you the exact method for getting this bug. I don't have any other sound mods, so it's most likely related to the physics of sounds.

**Expected behavior**
The sound is displayed correctly in Lan

**Versions**
- Minecraft version 1.18.2
- Forge version - 1.40.60
- Mod version - soundphysics-forge-1.18.2-1.0.6

**Other mods**
Random crash report, not related to the problem, to show all mods and versions:
[crash-2022-07-30_09.12.18-client.txt](https://github.com/henkelmax/sound-physics-remastered/files/9226161/crash-2022-07-30_09.12.18-client.txt)

**Comment by henkelmax** [comment] 2022-07-30 11:53
Please send me the full logs and a recording of the issue.

**Comment by BlackAures1** [comment] 2022-07-30 11:55
As you wish https://drive.google.com/file/d/1uTPWE-6_h7BhC2MWY4Wh3l0W-yRcMRFq/view?usp=sharing

**Comment by BlackAures1** [comment] 2022-07-30 14:58
Okay, I was able to clearly record the sound problem. At the very beginning you can see how the sounds randomly disappear and after teleporting to another dimension everything is fine again. https://youtu.be/DL9FwmCDAdY
If need be I have just another 10 minutes of footage of me just running around the Nether and all the sounds are saved.  But I don't see any point in that x) I've given plenty of information

**Comment by henkelmax** [comment] 2022-07-30 15:27
It seems like you multi block breaking overloads the sound system by trying to play too many sounds at once. Can you confirm that this also happens with no other mods installed?

**Comment by BlackAures1** [comment] 2022-07-30 16:01
These sounds disappear even when I'm not digging massively.  I really do not plan to play for 2-3 hours without mods just to check it :3 My job is to warn you.

**Comment by henkelmax** [comment] 2022-07-30 17:03
It this really only happens after multiple hours of playing, its not really feasible finding out wat or which mod causes the issue...
I simply don't have the time for that.
If you find out anything that could narrow down the cause, please let me know. 
But for now I'm closing the issue. Once there is more information I will re open it.

**Closed by henkelmax** 2022-07-30 17:03 UTC
Labels: bug

**Comment by SaltSouls** [comment] 2022-08-17 09:53
Hate to resurrect this, but I have also experienced this bug, though mine is exclusively isolated to the nether(haven't checked the end). It seems to happen after usually about 10-30 minutes of playing within the nether. Going back and forth between dimensions seems to fix it temporarily, but it is a problem as the nether is arguably one of the only areas in the game where having audio is very important.

I have a strong suspicion that this is being caused by the amount of sounds playing and the reverb of the nether dimension. I assume the two end up fighting each other until the cancel each other out(?). Adding more mods that add sounds(entity mods) causes this issue to speed up(or at least I think it does).

**Comment by SaltSouls** [comment] 2022-08-17 10:00
The only mods I have that really touch upon the nether(In order of most likely cause) would be Infernal Expansion, Alex's Mobs, Amplified Nether, Malum, Nethers Delight, and Nether Portal Fix. The last the are highly unlikely as they add either only a couple blocks, or make changes to existing mobs/systems of the nether(non having to do with audio). Amplified Nether is also an unlikely cause, but the heightened terrain could be causing issues with the sound systems in the dimension(?). Not sure, but I guess it could be a cause.

**Comment by BlackAures1** [comment] 2022-08-17 10:01
Yes. This problem still persists for me too. The easiest solution for the developer here is to add a optional configuration that will disable the mod in some dimension. Because in the upper world I never have perceptible sound problems, but the lower world breaks, given that there are minimal mods and creatures there.

This mod is really very good, but I understand if the developer doesn't want to mess with it. We all often get tired of our own projects too.

**Comment by SaltSouls** [comment] 2022-08-17 10:06
> Because in the upper world I never have perceptible sound problems, but the lower world breaks, given that there are minimal mods and creatures there.

So are you only getting this in the Nether as well, or is it in multiple dimensions? If so, which ones? That would be the kind of info the mod dev needs to actually attempt any fixes. If you are going to report a bug, it is customary to give as much information as is needed to help fix it. I've given my likely causes, but if you have any other mods you might suspect are causing issues, then I would probably list them off so that the dev can at least look to see if they are the cause or not.

**Comment by BlackAures1** [comment] 2022-08-18 22:13
I sent logs, list mods, recorded the video and described in detail absolutely everything I could. What else can I write here? The number of sounds in the Nether as measured by F3 is indeed much greater than in the upper world. About 15 versus 80-120 in Nether. Mass ore extraction has no effect on the number of sounds. I do not have any suspicions about. 

I know how hard to fix these things (I also develop mod), but I honestly do not want to spend a lot of time testing other people's mods.  If it gets too annoying about this bug I'll just delete the mod. For this reason I do **not insist** on fixing this bug. My job is just to warn.

**Comment by danbikes** [comment] 2022-10-22 00:26
I'm having the same issue as the other people above. After a few minutes of staying in one place that has a lot of sounds playing at once, the sounds start to slowly stop playing until the game goes completely quiet. It happens to me most often in the overworld, but I've had it happen to me in The Nether as well on occasion.

Traveling to another dimension, and going to the main game menu and then joining back temporarily fixes the issue, but it happens again just as it did before. 

I'm using the same mod pack as BlackAures1 btw, although I'm on Forge 40.1.73, Minecraft Version 1.18.2.

**Comment by SaltSouls** [comment] 2022-10-22 07:06
I have a theory about this. I think Minecraft's sound engine is being overloaded when using this mod as I imagine the way this works is by recreating and playing back the sounds at various levels of reverb in order to produce the desired effect. The problem is likely coming about because of the amount of sounds trying to stream through being too many for the engine to handle, resulting in it culling sounds repeatedly until eventually nothing is playing anymore. You can kinda hear this happen in the Nether(play there for about 15-30 minutes), where various sounds will slowly start to fade out, eventually ending with player generated noises such as breaking blocks, footsteps or picking up items.

**Comment by henkelmax** [comment] 2022-10-22 08:30
> I have a theory about this. I think Minecraft's sound engine is being overloaded when using this mod as I imagine the way this works is by recreating and playing back the sounds at various levels of reverb in order to produce the desired effect. The problem is likely coming about because of the amount of sounds trying to stream through being too many for the engine to handle, resulting in it culling sounds repeatedly until eventually nothing is playing anymore. You can kinda hear this happen in the Nether(play there for about 15-30 minutes), where various sounds will slowly start to fade out, eventually ending with player generated noises such as breaking blocks, footsteps or picking up items.

Thats not how this mod works.

**Comment by SaltSouls** [comment] 2022-10-22 08:44
> 
> Thats not how this mod works.
> 
> 

Well there goes that theory. All I know is something about this mod is fucking with their sound engine in areas with high amounts of sounds playing. That or maybe it's the fact that this mod is getting hung up on making reverb in the nether because it is basically a massive cave, though I feel like the last one there probably isn't the case.

**Comment by danbikes** [comment] 2022-10-22 22:16
>
> Thats not how this mod works.

Is there really nothing to suggest that the default number of sounds that Minecraft can play (iirc something like 28 at once before it starts culling sounds) has nothing to do with it? I've seen mods (albeit only for Fabric sadly, so I can't test to see if it helps) that address this specific problem on Curseforge, although it doesn't make sense to me why this issue only presents itself with this particular mod installed if that were the case since the number of sounds wouldn't change with/without the mod installed.

Just to test it, I've been playing without Sound Physics installed, and haven't run into any issues with sounds cutting out even when playing for 3+ hours at a time.
