### ISSUE TITLE
Sound Occlussion not working correctly with jukeboxes

### ISSUE THREAD

**Issue by TheDawnFox** [henkelmax/sound-physics-remastered#108] opened 2023-05-06 18:47 UTC
Sound Occlussion on jukeboxes doesnt work at all

**Versions**
- 1.18.2
- Forge
- Mod version 5.0.0.4

**Other mods**
Dynamic Surroundings

**Comment by henkelmax** [comment] 2023-05-06 21:51
Duplicate of #89

**Closed by henkelmax** 2023-05-06 21:51 UTC
Labels: bug
