### ISSUE TITLE
Doors make absolutely no noise in some situations.

### ISSUE THREAD

**Issue by djmrFunnyMan** [henkelmax/sound-physics-remastered#196] opened 2024-03-14 23:07 UTC
### Bug description

Doors make absolutely no noise in some situations. This particular setup causes the door to make no noise when closing.

### Minecraft version

1.20.4

### Mod version

1.20.4-1.3.1

### Mod loader and version

Fabric Loader 0.15.7

### Steps to reproduce

Reproduce the setup from the video. (Door is: facing=west, hinge=left)

### Log files

https://gist.github.com/djmrFunnyMan/36d2b43e41b5552e0319d6b602c0c5d9

### Videos

https://github.com/henkelmax/sound-physics-remastered/assets/68905776/f45d075e-11fd-4075-a0b3-8e17a5ba7d5d

**Comment by djmrFunnyMan** [comment] 2024-03-14 23:15
Here's a video with debug stuffs

https://github.com/henkelmax/sound-physics-remastered/assets/68905776/3161bed4-f61a-4a05-ad16-9e62235c677d

**Comment by henkelmax** [comment] 2024-03-15 08:03
Duplicate of #193

**Closed by henkelmax** 2024-03-15 08:03 UTC
Labels: duplicate
