### ISSUE TITLE
Muffled water noises

### ISSUE THREAD

**Issue by Pseudoentropy** [henkelmax/sound-physics-remastered#162] opened 2023-11-01 00:34 UTC
**Bug description**
Sound is muffled when using boats or when underwater.

**Steps to reproduce the issue**
1. Install the mod
2.  Use a boat in water and/or swim underwater and hit entities.

**Log files**
https://gist.github.com/Pseudoentropy/c0d88295ddf313a8d89de3cd93cfc88b

**Versions**
- 1.20.1
- Fabric 14.22
- 1.20.1-1.2.1

**Other mods**
cloth config, mod menu, fabric API

**Comment by henkelmax** [comment] 2023-11-01 08:08
Duplicate of #149

**Closed by henkelmax** 2023-11-01 08:08 UTC
Labels: triage
