### ISSUE TITLE
SPR causes java runtime environment fatal error

### ISSUE THREAD

**Issue by LunarPidgeon** [henkelmax/sound-physics-remastered#257] opened 2024-10-27 05:14 UTC
### Bug description

When attempting to launch minecraft with SPR and fabric/quilt, the JRE crashes and the game window freezes when the loading bar reaches about 90%.

### Minecraft version

1.20.1

### Mod version

1.20.1-1.4.5

### Mod loader and version

Fabric Loader 0.16.7 / Quilt Loader 0.26.4 

### Steps to reproduce

Install fabric or quilt to minecraft version 1.20.1
Install sound physics remastered
Launch game
Observe the JRE crash

### Expected behavior

Expected behavior: game loads as normal

### Log files

https://gist.github.com/LunarPidgeon/f14a52c81a1aa7f3c7b71b10be69e6df
https://gist.github.com/LunarPidgeon/4e1dbaa3ae4ece8f8062ca1382bb12f3

### Videos

Video is irrelevant.

**Comment by henkelmax** [comment] 2024-10-27 07:53
Duplicate of #143

**Closed by henkelmax** 2024-10-27 07:53 UTC
Labels: triage
