### ISSUE TITLE
Sounds cut off underwater in 1.20.1

### ISSUE THREAD

**Issue by DrakeFruit** [henkelmax/sound-physics-remastered#157] opened 2023-10-22 20:26 UTC
**Bug description**
when underwater, I cant hear any sounds that aren't at head height, unless I dig down a few blocks

**Steps to reproduce the issue**
1. Go underwater
2. No audio above or below
3. Dig a few blocks down underwater
4. Audio is back

**Expected behavior**
The audio should just be a little muffled, not completely cut off.

**Log files**
https://gist.github.com/DrakeFruit/48b9a4b9933b461c120c5b5ae89fb84f

**Versions**
- Minecraft version: 1.20.1
- Fabric loader version: 0.14.23
- Mod version: 1.20.1-1.2.1

**Other mods**
Issue occurs with no other mods installed

**Video**
https://github.com/henkelmax/sound-physics-remastered/assets/94070205/43b4d242-d9f6-4472-94d1-436672513244

**Comment by henkelmax** [comment] 2023-10-23 06:52
Duplicate of #149

**Closed by henkelmax** 2023-10-23 06:52 UTC
Labels: triage
