### ISSUE TITLE
Huge FPS drop when near alot of animals/sound producing stuff

### ISSUE THREAD

**Issue by KaoIdaJeste** [henkelmax/sound-physics-remastered#227] opened 2024-07-04 23:09 UTC
### Bug description

Huge FPS drops when near passive mobs

https://www.reddit.com/r/CreateMod/comments/12anvhs/huge_fps_drop_when_using_steam_engines_i_want_to/

Another case I've found which helped me identify the issue

Any possibility to add an option to disable certain sounds from casting rays? Like all passive mobs, for example.

### Minecraft version

1.20.4

### Mod version

1.20.4-1.4.2

### Mod loader and version

Fabric Loader 0.15.11

### Steps to reproduce

1. Have SPR mod
2. Be near large amount of sound producing stuff

### Expected behavior

Huge FPS drops

### Log files

not needed

### Videos

not needed

**Comment by henkelmax** [comment] 2024-07-05 07:07
Duplicate of #224

**Closed by henkelmax** 2024-07-05 07:07 UTC
Labels: triage
