### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by AltBrian379** [henkelmax/sound-physics-remastered#5] opened 2021-11-03 02:10 UTC
**Bug description**
Crash on startup

**Steps to reproduce the issue**
Pressing play on the Minecraft launcher.

**Expected behavior**
Launch Minecraft with mod loaded. 

**Log files**
No log file, <previous was wrong event. >

Exit code: 0

**Versions**
- 1.17.1
- 1.17.1-37.0.84
- 1.0.0

**Other mods**
Tested with no other mods.

**Comment by henkelmax** [comment] 2021-11-03 08:02
Update to the latest version. This has already been fixed.
Duplicate of #1 
Next time provide logs when reporting a bug.

**Closed by henkelmax** 2021-11-03 08:02 UTC
Labels: bug
