### ISSUE TITLE
Ignore Barrier blocks when reflecting sounds

### ISSUE THREAD

**Issue by KabanFriends** [henkelmax/sound-physics-remastered#70] opened 2022-10-15 09:58 UTC
In maps where there is a barrier roof, everything sounds as if I'm in a really large room. While this is technically true, I think it would be nice to have an option to ignore barrier blocks when calculating the sound reflections.

**Comment by henkelmax** [comment] 2022-10-15 14:44
Duplicate of #69

**Closed by henkelmax** 2022-10-15 14:44 UTC
Labels: enhancement
