### ISSUE TITLE
Cave Sounds being muffled or reverbed

### ISSUE THREAD

**Issue by Soabac** [henkelmax/sound-physics-remastered#228] opened 2024-07-07 08:47 UTC
### Bug description

i'm not 100% sure this is a bug ? but its weird and sort of breaks the experience nonetheless. basically what happens is im in a big cave, and a cave sound happens while i was digging down from that big cave, causing me to be away from where the cave sound "happened", and it being muffled because i would technically be "hidden" from the sound. straight up doesn't make sense ? i would like to hear that cave sound everywhere  i am in caves.

### Minecraft version

1.21

### Mod version

v1.21-1.4.3

### Mod loader and version

Quilt Loader 0.26.0

### Steps to reproduce

go in huge cave wait for mood % to go up then right when it happens hide yourself in a way to make sounds muffled around you

### Expected behavior

expected it to not get muffled. or reverbed for that matter, but that's less annoying

### Log files

not even a remote idea of how that would help/ where in a log this would be specified

### Videos

https://github.com/henkelmax/sound-physics-remastered/assets/125238031/cf367ea6-ecee-4598-a993-67f06755d6e0

**Comment by henkelmax** [comment] 2024-07-07 09:49
Duplicate of #177
Has been fixed by 19d8b5ad1abc54a3b50cc8161a999e2b12112df5

Please make sure you don't have the evaluate ambient sounds config option enabled.

**Closed by henkelmax** 2024-07-07 09:49 UTC
Labels: triage

**Comment by Soabac** [comment] 2024-07-07 10:57
cant believe i hadnt seen that !! i could not be more sorry!!
