### ISSUE TITLE
There is considerable lag when many sounds are played concurrently

### ISSUE THREAD

**Issue by AndreiToroplean** [henkelmax/sound-physics-remastered#234] opened 2024-07-18 20:51 UTC
### Bug description

So for example if you have a pen containing many animals, all making noises, and you get close to it, Minecraft starts to lag. 

I've looked through the mod's performance settings, and I've found no way to limit the total number of rays that exist at once. Reducing the number of rays per sound reduces the lag, but it's a shame to do that when most of the gameplay doesn't have that issue. I think that adding that setting could be a potential solution, especially since it's humanly difficult to make sense of many sounds at once and their places in space, so a drop in sound physics quality would probably not be very noticeable there.

### Minecraft version

1.20.4

### Mod version

fabric-1.20.4-1.4.5

### Mod loader and version

Fabric Loader 0.16.0

### Steps to reproduce

1. Create a pen using fences
2. Add many (>50) sheep inside it
3. Get close to it -> starts lagging
4. Get farther away -> when you can't hear the sheep, the lag is gone.

### Log files

https://gist.github.com/AndreiToroplean/89e08472f69371014f489b343aa1c565

### Videos

https://youtu.be/XodG4Acw3ak

**Comment by henkelmax** [comment] 2024-07-19 06:31
This is completely normal. The mod does a LOT of processing for every sound. If you have sounds that are played a lot, I'd recommend blacklisting the sound from being processed by the mod. Other than that you can adjust the performance settings.

**Comment by henkelmax** [comment] 2024-07-19 06:31
Also a duplicate of #227

**Closed by henkelmax** 2024-07-19 06:31 UTC
Labels: triage
