### ISSUE TITLE
Causes a SIGFPE error on Linux

### ISSUE THREAD

**Issue by Ankow99** [henkelmax/sound-physics-remastered#222] opened 2024-06-25 04:55 UTC
### Bug description

Using this mod causes a fatal error that prevents the game from starting on Linux, at least on versions 1.19.2 and 1.20.1. Various modpacks were not working for me with the same error. I discarded the Java version (I tried Java 17, OpenJDK 17, OpenJDK 21, Temurin 17, and Temurin 21). All runtimes had the same error. I removed each mod from various modpacks until I found that this mod was causing the fatal error on both modpacks; removing it solved the issue completely.

### Minecraft version

1.19.2

### Mod version

1.19.2-1.0.18

### Mod loader and version

Forge 43.3.0

### Steps to reproduce

1. Install mod's .jar in Mods folder using Linux
2. Try to launch game
3. Game CTDs after Mojang loading screen
4. Throws:
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGFPE (0x8) at pc=0x00007dfff5e9fb4d, pid=25261, tid=25541

### Expected behavior

The game launches and works

### Log files

https://gist.github.com/Ankow99/5d7a7bfe926b0592299aa73a5f16fae0

### Videos

I didn't record it

**Comment by henkelmax** [comment] 2024-06-25 06:39
Duplicate of #143

**Closed by henkelmax** 2024-06-25 06:39 UTC
Labels: triage
