### ISSUE TITLE
Audio distortion/reverb when walking on grass

### ISSUE THREAD

**Issue by Ninetalerise** [henkelmax/sound-physics-remastered#237] opened 2024-07-21 02:52 UTC
### Bug description

There is a noticable distortion/reverb when walking on grass blocks. No other mods were installed while conducting my tests.

### Minecraft version

1.20,1

### Mod version

1.20,1-1.4.5

### Mod loader and version

Forge 47.3.5

### Steps to reproduce

1. Install sound-physics-remastered-forge-1.20.1-1.4.5.jar on Forge 47.3.5
2. Create new world
3. Walk on grass blocks

### Expected behavior

Normal sounding walking as seen in the default minecraft video

### Log files

https://gist.github.com/Ninetalerise/365efefa20c47a79d0506bdccfbe78b2

### Videos

https://github.com/user-attachments/assets/aec9f8e1-7fd3-4d01-b5e0-cb90e8b9cb06

https://github.com/user-attachments/assets/3a6c4544-a415-4ba5-8fd0-ba3e2b32e6a0

**Comment by henkelmax** [comment] 2024-07-21 08:35
Duplicate of #202

**Closed by henkelmax** 2024-07-21 08:35 UTC
Labels: triage
