### ISSUE TITLE
Sounds randomly mute in 1.19.2 Forge

### ISSUE THREAD

**Issue by riley-9054** [henkelmax/sound-physics-remastered#83] opened 2022-12-13 07:25 UTC
**Bug description**
Sometimes sounds will be silent when they're supposed to play

**Steps to reproduce the issue**
I have no Idea what causes it, the best thing I can say to reproduce it is go into the nether and just play the game for a while.

**Expected behavior**
The sounds play and I hear them.

**Log files**
latest.log: https://gist.github.com/riley-9054/859a3ebc702c6822b9876ea68c633782
There is no crash report as the game did not crash, I closed it manually.

**Versions**
- Minecraft 1.19.2
- Forge 43.1.43
- Sound Physics Remastered 1.0.15

**Other mods**
The only other mods I can think of that could affect this are Optifine, Infernal Expansion, Biomes O'Plenty, Gardens of the Dead, Immersive Weathering, or Better Block Sounds.

**Screenshots (Optional)**
Video of the bug in action, it's not always this bad it seems to have "phases" if that makes sense:
https://user-images.githubusercontent.com/117400609/207250789-e901afab-b3dd-4400-97a1-aa8806833842.mp4
Apologies if the video takes a while to load, I used the Xbox Game Bar to record it so the file size is quite large.

**Comment by henkelmax** [comment] 2022-12-13 07:32
This seems to be a duplicate of #54
This especially happens in heavily modded environments with a lot of sounds played (Doesn't necessarily need to be heard by the player).

**Comment by riley-9054** [comment] 2022-12-13 17:40
Is there some way for you to fix it? Most people who play with this mod are going to play with a good number of other mods as well.

**Comment by henkelmax** [comment] 2022-12-13 19:02
You can add sounds that are spammed too much that the sound engine can't handle it to the blacklist regex.

**Comment by riley-9054** [comment] 2022-12-13 23:30
Is there info anywhere on how the syntax of the blacklist regex works?

**Comment by henkelmax** [comment] 2022-12-14 07:04
Its just a simple regex that matches the sound ids.

https://www.debuggex.com/
https://regex101.com/
These are some great tools for creating regexes.

**Closed** 2022-12-20 12:34 UTC
Labels: bug
