### ISSUE TITLE
Crash - 1.19.2 Forge 43.4.2 

### ISSUE THREAD

**Issue by nnra6864** [henkelmax/sound-physics-remastered#243] opened 2024-08-11 05:41 UTC
### Bug description

Minecraft crashes on launch.
I've isolated sound physics as the issues because the game launches just fine with it disabled.

### Minecraft version

1.19.2

### Mod version

1.19.2-1.4.5

### Mod loader and version

Forge 43.4.2

### Steps to reproduce

Crashes on launch

### Expected behavior

For game to launch

### Log files

https://gist.github.com/nnra6864/ee4fc7c5b8a7543ce45f23ba372548a6
https://mclo.gs/GyzEXMO

### Videos

I don't have a video of it

**Comment by henkelmax** [comment] 2024-08-11 07:02
Duplicate of #143

**Closed by henkelmax** 2024-08-11 07:02 UTC
Labels: triage
