### ISSUE TITLE
Sound conflict with Zombie Awareness?

### ISSUE THREAD

**Issue by jackg2527** [henkelmax/sound-physics-remastered#22] opened 2022-01-02 07:51 UTC
**Bug description**

Hi there, when I use this mod with Zombie Awareness, some sounds are muted: zombie growling and other mob sounds, mobs reaction to damage, no sound when firing bow. Other sounds such as hitting/breaking blocks are not affected. Looks like same issue posted yesterday  https://github.com/henkelmax/sound-physics-remastered/issues/21#issue-1091666987

If I remove Sound Physics **OR** Zombie Awareness, all sounds are back to normal. Will also post this on ZA site. 

Anything you guys could do would be greatly appreciated. Two of my favorite mods and trying to choose between them is just...killing...me.

Many thanks!
Jack

**Versions**
zombieawareness-1.18.1-1.12
coroutil-1.18.1-1.2.37
soundphysics-forge-1.18.1-1.0.3
Forge: 39.0.9 

**Steps to reproduce the issue**
See above.

**Expected behavior**
Normal sounds!

**Log files**
I'm attaching latest.log and debug.log files since I dunno what will help you. Four files:
- ZAonly_: latest and debug with just ZA and CoroUtil installed, all sounds working
- ZAandSoundPhys_: same files after adding Sound physics, sound issue occurs

[ZAonly_latest.log](https://github.com/henkelmax/sound-physics-remastered/files/7798748/ZAonly_latest.log)
[ZAonly_debug.log](https://github.com/henkelmax/sound-physics-remastered/files/7798749/ZAonly_debug.log)
[ZAandSoundPhys_latest.log](https://github.com/henkelmax/sound-physics-remastered/files/7798750/ZAandSoundPhys_latest.log)
[ZAandSoundPhys_debug.log](https://github.com/henkelmax/sound-physics-remastered/files/7798751/ZAandSoundPhys_debug.log)

**Comment by henkelmax** [comment] 2022-01-02 08:09
Duplicate of #21

**Closed** 2022-01-02 08:10 UTC
Labels: duplicate
