### ISSUE TITLE
1.16.5 version

### ISSUE THREAD

**Issue by toasterdoggg** [henkelmax/sound-physics-remastered#122] opened 2023-07-10 08:55 UTC
Hey! I was disappointed to see that this mod only has versions extending back to 1.17. Unfortunately I only play on 1.16.5 due to the server I'm active on being set to that version. I'd like to know if you plan to, at some point, backport the mod to 1.16.5 or is there some technical limitation that would make that infeasible?

**Comment by henkelmax** [comment] 2023-07-10 10:30
Duplicate of #49

**Closed by henkelmax** 2023-07-10 10:30 UTC
Labels: enhancement
