### ISSUE TITLE
Fabric  incompatible with new Create 0.5.1f

### ISSUE THREAD

**Issue by Miamlya** [henkelmax/sound-physics-remastered#201] opened 2024-04-08 22:07 UTC
### Bug description

Game

### Minecraft version

1.20.1

### Mod version

1.20.1-1.3.1

### Mod loader and version

Fabric 0.15.9

### Steps to reproduce

1. Install Create 0.5.1f (last one)
2. Install Sound Physics Remastered
3. Start the game

### Log files

https://gist.github.com/Miamlya/868ce4e63213e1ce6a90fbcfa2952351

### Videos

-

**Comment by henkelmax** [comment] 2024-04-09 06:51
Duplicate of #172

**Closed by henkelmax** 2024-04-09 06:51 UTC
Labels: duplicate, invalid
