### ISSUE TITLE
Incompatible with Create

### ISSUE THREAD

**Issue by Bellabeau6** [henkelmax/sound-physics-remastered#208] opened 2024-05-06 15:31 UTC
### Bug description

I just went and updated the mods in my pack and now this mod is incompatible with Create.

### Minecraft version

1.20.1

### Mod version

1.3.0

### Mod loader and version

Fabric loader V 0.15.11

### Steps to reproduce

Install this mod with Create.
Run the client.
The game crashes and shows that the two mods are incompatible.

### Expected behavior

I expected to be able to boot into my modpack as I have done many times before despite the updates I had to install.

### Log files

https://gist.github.com/Bellabeau6/94ae96e830736a0895d93a52940470b1

### Videos

N/A

**Comment by henkelmax** [comment] 2024-05-06 16:43
Duplicate of #172

**Closed by henkelmax** 2024-05-06 16:43 UTC
Labels: triage
